id: D04AC47BB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T14:01:25+00:00'
last_modified: '2022-05-30T06:27:55.259676+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    6a4a:
      image_group_id: I1PD95961
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་སྨོན་ལམ།
      total_pages: 1880
      order: 116
      base_file: 6a4a.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
