id: PD469CEB9
initial_creation_type: ocr
source_metadata:
  volumes:
    c23c197236284776ab03805d460cebdd:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་སྨོན་ལམ།
      total_pages: 1880
      volume_number: 116
